name: Python application

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '30 0 * * *'
    - cron: '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        
    - name: running
      run: |
        python3 daily-reminder.py
        	

